ui <- fluidPage(
  titlePanel('COVID-19 cases and deaths visualisation generator'),
  sidebarLayout(
    sidebarPanel(width = 3,
                 checkboxInput(inputId = 'x_marker',
                               label = 'Add death markers? (cases charts only)',
                               value = F),
                 checkboxInput(inputId = 'int_marker',
                               label = 'Add intervention markers?',
                               value = F),
                 numericInput('x_start',
                              label = 'Start graph at x cases/deaths',
                              value = 100,
                              min = 10,
                              max = 200,
                              step = 10),
                 selectInput('start_type',
                             label = 'Start graph at cases or death mark',
                             choices = c('case', 'death'),
                             selected = 'case'),
                 selectInput('x_type',
                             label = 'X-axis type',
                             choices = c('Days since x', 'date'),
                             selected = 'Days since'),
                 numericInput('day_start',
                              label = 'Start graph at day y after x cases/deaths',
                              value = 0,
                              min = 0,
                              max = 100,
                              step = 10),
                 selectInput('percap',
                             label = 'Per population size?',
                             choices = c('not transformed', 'per million'),
                             selected = 'not transformed'),
                 selectInput(inputId = 'y_trans',
                             label = 'Y-axis transformation',
                             selected = 'log10',
                             choices = c('log10', 'identity')),
                 checkboxGroupInput(inputId = 'countries', 
                                    label = 'Countries to include', 
                                    choices = countries, 
                                    selected = countries,
                                    inline = FALSE),
                 selectizeInput(inputId = 'add_countries',
                                label = 'Additional countries',
                                choices = add_countries,
                                multiple = TRUE),
                 checkboxGroupInput(inputId = 'categories', 
                                    label = 'Categories of interventions to include', 
                                    choices = unique(interventions$int), 
                                    selected = 'lockdown',
                                    inline = FALSE),
                 selectInput(inputId = 'letter_marker',
                             label = 'Which intervention markers?',
                             choices = c('Categories', 'Individual letters'),
                             selected = 'Categories'),
                 hr(),
                 h3('Visual graph settings'),
                 numericInput(inputId = 'text_size',
                              label = 'Text size', 
                              value = 4, 
                              min = 0.4, 
                              max = 10,
                              step = 0.1),
                 numericInput(inputId = 'line_size',
                              label = 'Line width',
                              value = 0.8,
                              min = 0.1,
                              max = 2.0,
                              step = 0.1),
                 numericInput(inputId = 'xlabel_size',
                              label = 'Marker size',
                              value = 3,
                              min = 0.5,
                              max = 10,
                              step = 0.5),
                 numericInput(inputId = 'text_move',
                              label = 'Text movement (to avoid overlap)', 
                              value = 0, 
                              min = 0.0001, 
                              max = 1,
                              step = 0.0001)
    ),
    mainPanel(width = 9,
              p('This tool loads JHU cases and deaths data and provides visualisations of cumulative and new cases and deaths over time. Use the options on the left-hand side to change what is visualised.'),
              tabsetPanel(type = "tabs",
                          tabPanel("Confirmed cases", 
                                   h1('Confirmed cases'),
                                   plotOutput("graph_conf"),
                                   hr(),
                                   h3('Raw data'),
                                   dataTableOutput(outputId = "data_conf")),
                          tabPanel("Confirmed deaths",
                                   h1('Confirmed deaths'),
                                   plotOutput("graph_death"),
                                   hr(),
                                   h3('Raw data'),
                                   dataTableOutput(outputId = "data_death")),
                          tabPanel("Rolling averages", 
                                   h1('Rolling averages'),
                                   numericInput(inputId = 'roll_num',
                                                label = 'Rolling average: x days', 
                                                value = 3, 
                                                min = 3, 
                                                max = 14,
                                                step = 1),
                                   hr(),
                                   plotOutput('roll_deaths'),
                                   hr(),
                                   plotOutput('roll_cases'),
                                   hr(),
                                   plotOutput("roll_both"),
                                   hr(),
                                   h3('Raw data'),
                                   dataTableOutput(outputId = "roll_data")),
                          tabPanel("Maps",
                                   h3("Latest maps of cumulative cases and deaths per 100k population"),
                                   plotOutput("case_map"),
                                   hr(),
                                   plotOutput("death_map"),
                                   hr(),
                                   dataTableOutput(outputId = "map_data")),
                          tabPanel("Interventions legend",
                                   h3('Legend of interventions'),
                                   dataTableOutput("data_int"),)
              )
    )
  )
)
